SELECT
    o.RAZAO_SOCIAL,
    d.VL_SALDO_FINAL
FROM demonstracoes_contabeis d
JOIN operadoras o ON d.REG_ANS = o.REG_ANS
WHERE d.DESCRICAO = 'EVENTOS/ SINISTROS CONHECIDOS OU AVISADOS DE ASSISTÊNCIA A SAÚDE MEDICO HOSPITALAR'
ORDER BY d.VL_SALDO_FINAL DESC
LIMIT 10;