
CREATE DATABASE dados_ans;
USE dados_ans;


CREATE TABLE demonstracoes_contabeis (
    DATA DATE,
    REG_ANS VARCHAR(10),
    CD_CONTA_CONTABIL VARCHAR(20),
    DESCRICAO VARCHAR(100),
    VL_SALDO_INICIAL DECIMAL(18,2),
    VL_SALDO_FINAL DECIMAL(18,2)
);

CREATE TABLE operadoras (
    REG_ANS VARCHAR(10),
    CNPJ VARCHAR(14),
    RAZAO_SOCIAL VARCHAR(100),
    NOME_FANTASIA VARCHAR(100),
    MODALIDADE VARCHAR(50),
    LOGRADOURO VARCHAR(100),
    NUMERO VARCHAR(10),
    COMPLEMENTO VARCHAR(50),
    BAIRRO VARCHAR(50),
    CIDADE VARCHAR(50),
    ESTADO VARCHAR(2),
    CEP VARCHAR(8),
    DDD VARCHAR(3),
    TELEFONE VARCHAR(10),
    FAX VARCHAR(10),
    EMAIL VARCHAR(100),
    REPRESENTANTE VARCHAR(100),
    CARGO_REPRESENTANTE VARCHAR(50),
    REGIAO_COMERCIALIZACAO VARCHAR(50),
    DATA_REGISTRO_ANS DATE
);